// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _2026_MT_Gerashchenko_A_S_Lab_2.Migrations
{
    [DbContext(typeof(BuildSystemDbContext))]
    [Migration("20260704221554_AddMatrixAnalyticsLookups")]
    partial class AddMatrixAnalyticsLookups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Entities.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId");

                    b.HasIndex("RepositoryPath")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Entities.BenchmarkTest", b =>
                {
                    b.Property<int>("BenchmarkTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("BenchmarkTestId");

                    b.HasIndex("TestDescription")
                        .IsUnique();

                    b.ToTable("BenchmarkTests");
                });

            modelBuilder.Entity("Entities.BuildExecution", b =>
                {
                    b.Property<int>("BuildExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutionResultId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutionStartTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessStageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildExecutionId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ExecutionResultId");

                    b.HasIndex("ProcessStageId");

                    b.ToTable("BuildExecutions");
                });

            modelBuilder.Entity("Entities.BuildMessage", b =>
                {
                    b.Property<int>("BuildMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ErrorCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageSeverityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MessageTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("BuildMessageId");

                    b.HasIndex("BuildExecutionId");

                    b.HasIndex("ErrorCodeId");

                    b.HasIndex("MessageSeverityId");

                    b.ToTable("BuildMessages");
                });

            modelBuilder.Entity("Entities.ErrorCode", b =>
                {
                    b.Property<int>("ErrorCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ErrorCodeId");

                    b.HasIndex("CodeValue")
                        .IsUnique();

                    b.ToTable("ErrorCodes");
                });

            modelBuilder.Entity("Entities.ExecutionResult", b =>
                {
                    b.Property<int>("ExecutionResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ExecutionResultId");

                    b.HasIndex("ResultName")
                        .IsUnique();

                    b.ToTable("ExecutionResults");
                });

            modelBuilder.Entity("Entities.MessageSeverity", b =>
                {
                    b.Property<int>("MessageSeverityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeverityDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeverityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("MessageSeverityId");

                    b.HasIndex("SeverityName")
                        .IsUnique();

                    b.ToTable("MessageSeverities");
                });

            modelBuilder.Entity("Entities.PerformanceMetric", b =>
                {
                    b.Property<int>("PerformanceMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenchmarkTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MetricRecordTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("MultiThreadTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SingleThreadTimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerformanceMetricId");

                    b.HasIndex("BenchmarkTestId");

                    b.HasIndex("BuildExecutionId");

                    b.HasIndex("ServerConfigurationId");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("Entities.ProcessStage", b =>
                {
                    b.Property<int>("ProcessStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessStageId");

                    b.HasIndex("StageName")
                        .IsUnique();

                    b.ToTable("ProcessStages");
                });

            modelBuilder.Entity("Entities.ProcessorModel", b =>
                {
                    b.Property<int>("ProcessorModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalCores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalCores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessorModelId");

                    b.HasIndex("ProcessorName")
                        .IsUnique();

                    b.ToTable("ProcessorModels");
                });

            modelBuilder.Entity("Entities.ServerConfiguration", b =>
                {
                    b.Property<int>("ServerConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MemoryCapacityGb")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ProcessorModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemEnvironmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerConfigurationId");

                    b.HasIndex("ProcessorModelId");

                    b.HasIndex("SystemEnvironmentId");

                    b.ToTable("ServerConfigurations");
                });

            modelBuilder.Entity("Entities.SystemEnvironment", b =>
                {
                    b.Property<int>("SystemEnvironmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentDetails")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SystemEnvironmentId");

                    b.HasIndex("EnvironmentName")
                        .IsUnique();

                    b.ToTable("SystemEnvironments");
                });

            modelBuilder.Entity("Entities.BuildExecution", b =>
                {
                    b.HasOne("Entities.Application", "Application")
                        .WithMany("BuildExecutions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.ExecutionResult", "ExecutionResult")
                        .WithMany("BuildExecutions")
                        .HasForeignKey("ExecutionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.ProcessStage", "ProcessStage")
                        .WithMany("BuildExecutions")
                        .HasForeignKey("ProcessStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ExecutionResult");

                    b.Navigation("ProcessStage");
                });

            modelBuilder.Entity("Entities.BuildMessage", b =>
                {
                    b.HasOne("Entities.BuildExecution", "BuildExecution")
                        .WithMany("BuildMessages")
                        .HasForeignKey("BuildExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.ErrorCode", "ErrorCode")
                        .WithMany("BuildMessages")
                        .HasForeignKey("ErrorCodeId");

                    b.HasOne("Entities.MessageSeverity", "MessageSeverity")
                        .WithMany("BuildMessages")
                        .HasForeignKey("MessageSeverityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildExecution");

                    b.Navigation("ErrorCode");

                    b.Navigation("MessageSeverity");
                });

            modelBuilder.Entity("Entities.PerformanceMetric", b =>
                {
                    b.HasOne("Entities.BenchmarkTest", "BenchmarkTest")
                        .WithMany("PerformanceMetrics")
                        .HasForeignKey("BenchmarkTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.BuildExecution", "BuildExecution")
                        .WithMany()
                        .HasForeignKey("BuildExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.ServerConfiguration", "ServerConfiguration")
                        .WithMany("PerformanceMetrics")
                        .HasForeignKey("ServerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkTest");

                    b.Navigation("BuildExecution");

                    b.Navigation("ServerConfiguration");
                });

            modelBuilder.Entity("Entities.ServerConfiguration", b =>
                {
                    b.HasOne("Entities.ProcessorModel", "ProcessorModel")
                        .WithMany("ServerConfigurations")
                        .HasForeignKey("ProcessorModelId");

                    b.HasOne("Entities.SystemEnvironment", "SystemEnvironment")
                        .WithMany("ServerConfigurations")
                        .HasForeignKey("SystemEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessorModel");

                    b.Navigation("SystemEnvironment");
                });

            modelBuilder.Entity("Entities.Application", b =>
                {
                    b.Navigation("BuildExecutions");
                });

            modelBuilder.Entity("Entities.BenchmarkTest", b =>
                {
                    b.Navigation("PerformanceMetrics");
                });

            modelBuilder.Entity("Entities.BuildExecution", b =>
                {
                    b.Navigation("BuildMessages");
                });

            modelBuilder.Entity("Entities.ErrorCode", b =>
                {
                    b.Navigation("BuildMessages");
                });

            modelBuilder.Entity("Entities.ExecutionResult", b =>
                {
                    b.Navigation("BuildExecutions");
                });

            modelBuilder.Entity("Entities.MessageSeverity", b =>
                {
                    b.Navigation("BuildMessages");
                });

            modelBuilder.Entity("Entities.ProcessStage", b =>
                {
                    b.Navigation("BuildExecutions");
                });

            modelBuilder.Entity("Entities.ProcessorModel", b =>
                {
                    b.Navigation("ServerConfigurations");
                });

            modelBuilder.Entity("Entities.ServerConfiguration", b =>
                {
                    b.Navigation("PerformanceMetrics");
                });

            modelBuilder.Entity("Entities.SystemEnvironment", b =>
                {
                    b.Navigation("ServerConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
