// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Data;

#nullable disable

namespace Migrations
{
    [DbContext(typeof(BuildSystemDbContext))]
    [Migration("20260614200422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId");

                    b.HasIndex("RepositoryPath")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BenchmarkTest", b =>
                {
                    b.Property<int>("BenchmarkTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("BenchmarkTestId");

                    b.HasIndex("TestDescription")
                        .IsUnique();

                    b.ToTable("BenchmarkTests");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BuildExecution", b =>
                {
                    b.Property<int>("BuildExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutionResultId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutionStartTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessStageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildExecutionId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ExecutionResultId");

                    b.HasIndex("ProcessStageId");

                    b.ToTable("BuildExecutions");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BuildMessage", b =>
                {
                    b.Property<int>("BuildMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ErrorCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageSeverityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MessageTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("BuildMessageId");

                    b.HasIndex("BuildExecutionId");

                    b.HasIndex("ErrorCodeId");

                    b.HasIndex("MessageSeverityId");

                    b.ToTable("BuildMessages");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ErrorCode", b =>
                {
                    b.Property<int>("ErrorCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ErrorCodeId");

                    b.HasIndex("CodeValue")
                        .IsUnique();

                    b.ToTable("ErrorCodes");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ExecutionResult", b =>
                {
                    b.Property<int>("ExecutionResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ExecutionResultId");

                    b.HasIndex("ResultName")
                        .IsUnique();

                    b.ToTable("ExecutionResults");

                    b.HasData(
                        new
                        {
                            ExecutionResultId = 1,
                            ResultDescription = "Execution completed successfully",
                            ResultName = "Passed"
                        },
                        new
                        {
                            ExecutionResultId = 2,
                            ResultDescription = "Execution encountered errors",
                            ResultName = "Failed"
                        },
                        new
                        {
                            ExecutionResultId = 3,
                            ResultDescription = "Execution was aborted",
                            ResultName = "Aborted"
                        },
                        new
                        {
                            ExecutionResultId = 4,
                            ResultDescription = "Execution is currently running",
                            ResultName = "InProgress"
                        });
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.MessageSeverity", b =>
                {
                    b.Property<int>("MessageSeverityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeverityDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeverityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("MessageSeverityId");

                    b.HasIndex("SeverityName")
                        .IsUnique();

                    b.ToTable("MessageSeverities");

                    b.HasData(
                        new
                        {
                            MessageSeverityId = 1,
                            SeverityDescription = "Critical compilation error",
                            SeverityName = "Error"
                        },
                        new
                        {
                            MessageSeverityId = 2,
                            SeverityDescription = "Non-blocking issue",
                            SeverityName = "Warning"
                        },
                        new
                        {
                            MessageSeverityId = 3,
                            SeverityDescription = "Informational notification",
                            SeverityName = "Info"
                        });
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.PerformanceMetric", b =>
                {
                    b.Property<int>("PerformanceMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenchmarkTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MetricRecordTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("MultiThreadTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SingleThreadTimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerformanceMetricId");

                    b.HasIndex("BenchmarkTestId");

                    b.HasIndex("BuildExecutionId");

                    b.HasIndex("ServerConfigurationId");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ProcessStage", b =>
                {
                    b.Property<int>("ProcessStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessStageId");

                    b.HasIndex("StageName")
                        .IsUnique();

                    b.ToTable("ProcessStages");

                    b.HasData(
                        new
                        {
                            ProcessStageId = 1,
                            StageName = "Compile"
                        },
                        new
                        {
                            ProcessStageId = 2,
                            StageName = "UnitTest"
                        },
                        new
                        {
                            ProcessStageId = 3,
                            StageName = "CodeAnalysis"
                        },
                        new
                        {
                            ProcessStageId = 4,
                            StageName = "Deploy"
                        });
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ProcessorModel", b =>
                {
                    b.Property<int>("ProcessorModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalCores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalCores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessorModelId");

                    b.HasIndex("ProcessorName")
                        .IsUnique();

                    b.ToTable("ProcessorModels");

                    b.HasData(
                        new
                        {
                            ProcessorModelId = 1,
                            LogicalCores = 32,
                            PhysicalCores = 16,
                            ProcessorName = "AMD Ryzen 9 7950X"
                        },
                        new
                        {
                            ProcessorModelId = 2,
                            LogicalCores = 32,
                            PhysicalCores = 24,
                            ProcessorName = "Intel Core i9-13900K"
                        },
                        new
                        {
                            ProcessorModelId = 3,
                            LogicalCores = 12,
                            PhysicalCores = 6,
                            ProcessorName = "AMD Ryzen 5 5600X"
                        });
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ServerConfiguration", b =>
                {
                    b.Property<int>("ServerConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MemoryCapacityGb")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ProcessorModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemEnvironmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerConfigurationId");

                    b.HasIndex("ProcessorModelId");

                    b.HasIndex("SystemEnvironmentId");

                    b.ToTable("ServerConfigurations");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.SystemEnvironment", b =>
                {
                    b.Property<int>("SystemEnvironmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentDetails")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SystemEnvironmentId");

                    b.HasIndex("EnvironmentName")
                        .IsUnique();

                    b.ToTable("SystemEnvironments");

                    b.HasData(
                        new
                        {
                            SystemEnvironmentId = 1,
                            EnvironmentName = "Windows 11 Pro (64-bit)"
                        },
                        new
                        {
                            SystemEnvironmentId = 2,
                            EnvironmentName = "Windows 10 Pro (64-bit)"
                        },
                        new
                        {
                            SystemEnvironmentId = 3,
                            EnvironmentName = "Ubuntu 24.04 LTS (64-bit)"
                        },
                        new
                        {
                            SystemEnvironmentId = 4,
                            EnvironmentName = "macOS Sequoia 15"
                        });
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BuildExecution", b =>
                {
                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.Application", "Application")
                        .WithMany("BuildExecutions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ExecutionResult", "ExecutionResult")
                        .WithMany("BuildExecutions")
                        .HasForeignKey("ExecutionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ProcessStage", "ProcessStage")
                        .WithMany("BuildExecutions")
                        .HasForeignKey("ProcessStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ExecutionResult");

                    b.Navigation("ProcessStage");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BuildMessage", b =>
                {
                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BuildExecution", "BuildExecution")
                        .WithMany("BuildMessages")
                        .HasForeignKey("BuildExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ErrorCode", "ErrorCode")
                        .WithMany("BuildMessages")
                        .HasForeignKey("ErrorCodeId");

                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.MessageSeverity", "MessageSeverity")
                        .WithMany("BuildMessages")
                        .HasForeignKey("MessageSeverityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildExecution");

                    b.Navigation("ErrorCode");

                    b.Navigation("MessageSeverity");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.PerformanceMetric", b =>
                {
                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BenchmarkTest", "BenchmarkTest")
                        .WithMany("PerformanceMetrics")
                        .HasForeignKey("BenchmarkTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BuildExecution", "BuildExecution")
                        .WithMany()
                        .HasForeignKey("BuildExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ServerConfiguration", "ServerConfiguration")
                        .WithMany("PerformanceMetrics")
                        .HasForeignKey("ServerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkTest");

                    b.Navigation("BuildExecution");

                    b.Navigation("ServerConfiguration");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ServerConfiguration", b =>
                {
                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ProcessorModel", "ProcessorModel")
                        .WithMany("ServerConfigurations")
                        .HasForeignKey("ProcessorModelId");

                    b.HasOne("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.SystemEnvironment", "SystemEnvironment")
                        .WithMany("ServerConfigurations")
                        .HasForeignKey("SystemEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessorModel");

                    b.Navigation("SystemEnvironment");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.Application", b =>
                {
                    b.Navigation("BuildExecutions");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BenchmarkTest", b =>
                {
                    b.Navigation("PerformanceMetrics");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.BuildExecution", b =>
                {
                    b.Navigation("BuildMessages");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ErrorCode", b =>
                {
                    b.Navigation("BuildMessages");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ExecutionResult", b =>
                {
                    b.Navigation("BuildExecutions");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.MessageSeverity", b =>
                {
                    b.Navigation("BuildMessages");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ProcessStage", b =>
                {
                    b.Navigation("BuildExecutions");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ProcessorModel", b =>
                {
                    b.Navigation("ServerConfigurations");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.ServerConfiguration", b =>
                {
                    b.Navigation("PerformanceMetrics");
                });

            modelBuilder.Entity("_2026_MT_Gerashchenko_A_S_Lab_2.Entities.SystemEnvironment", b =>
                {
                    b.Navigation("ServerConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
