<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>_2026MTGerashchenkoASLab5</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
		<NoWarn>SA0001,SA1600,SA1633</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.57.2" />

		<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="..\code-analysis.ruleset" Link="Properties\code-analysis.ruleset" />
		<AdditionalFiles Include="..\stylecop.json" Link="Properties\stylecop.json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\2026_MT_Gerashchenko_A_S_Lab_2\2026MTGerashchenkoASLab2.csproj" />
	  <ProjectReference Include="..\MT_LAB3.MatrixGenerator\MTLAB3.MatrixGenerator.csproj" />
	  <ProjectReference Include="..\MT_LAB3.MatrixLib\MTLAB3.MatrixLib.csproj" />
	  <ProjectReference Include="..\MT_LAB3.PerformanceTest\MTLAB3.PerformanceTest.csproj" />
	</ItemGroup>

</Project>